# Generated by Django 4.2.3 on 2023-07-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=30)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=40)),
                ('phoneno', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('licence_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=40)),
                ('vehicle_color', models.CharField(max_length=40)),
                ('vehicle_number', models.CharField(max_length=40)),
                ('venicle_type', models.CharField(max_length=40)),
                ('vehicle_photo', models.ImageField(upload_to='photos')),
                ('vehicle_description', models.TextField()),
                ('rent_per_day', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ratings', models.CharField(max_length=25)),
                ('comments', models.CharField(max_length=50)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_duration', models.DateField()),
                ('from_to', models.DateField()),
                ('amount', models.CharField(max_length=35)),
                ('reciept', models.ImageField(null=True, upload_to='reciepts')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('paystatus', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle_table')),
            ],
        ),
    ]
